server:
  port: 8228
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.12.101.116:3306/theme_story?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://sh-cynosdbmysql-grp-bqiikk8u.sql.tencentcdb.com:24895/theme_story?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: Abel123456
    druid:
      initial-size: 5   # 初始化大小
      min-idle: 5       # 最小空闲连接个数
      max-active: 20    # 最大连接个数
      max-wait: 60000   # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次监测，监测需要关闭的空闲连接，单位时毫秒
      min-evictable-idle-time-millis: 60000       # 配置一个连接在池中最小生存的时间
      validation-query: select 'x'                # 用来监测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true            # 建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      pool-prepared-statements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
      aop-patterns: com.qxm.themestory.*
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          config:
            drop-table-allow: false
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.46.120
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.46.121
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
logging:
  level:
    com.qxm: DEBUG
    com.ejlchina.searcher: DEBUG
#  config: classpath:logback-spring.xml
mybatis:
  type-aliases-package: com.qxm.**.entity
  mapper-locations: classpath*:com/qxm/**/mapper/*.xml
  configuration:
    call-setters-on-nulls: true

qxm:
  wechat:
    appid: wxefd322904e8fe89d
    secret: 65bf1d3ce610d88f4b5394977d98fed4
